## 1.2 A Tutorial Example

    For the newcomer to the field of machine learning, many of the basic concepts and
    much of the terminology can be introduced in the context of a simple example in-
    volving the fitting of a polynomial to a small synthetic data set (Bishop, 2006). This
    is a form of supervised learning problem in which we would like to make a prediction
    for a target variable, given the value of an input variable.

#### 1.2.1 Syntethic Data

    We denote the input variable by x and the target variable by t, and we assume
    that both variables take continuous values on the real axis. Suppose that we are
    given a training set comprising N observations of x, written x1 , . . . , xN , together
    with corresponding observations of the values of t, denoted t1 , . . . , tN . Our goal
    is to predict the value of t for some new value of x. The ability to make accurate
    predictions on previously unseen inputs is a key goal in machine learning and is
    known as generalization.

In [6]:
# import desired libraries
import numpy as np
import matplotlib.pyplot as plt
import math

In [11]:
# set a few constantes
SEED = 42
N = 100 # The number of samples in our training set.

In [3]:
# make this code sample reproducable
np.random.seed(SEED)

<img src="../images/numpy.random.rand.png" alt="Numpy random rand" width="360">

In [4]:
np.random.rand(3, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [7]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
list(range(1, 16))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [19]:
def linearFunction(x, addNoise=False):

    # we set the value of our linear function here ... 
    returnValue = (2 * math.pi * x)

    if addNoise:
        returnValue += np.random.rand()

    return returnValue

    

In [17]:
X = np.arange(1,N)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
linearFunction(X, False)

array([  6.28318531,  12.56637061,  18.84955592,  25.13274123,
        31.41592654,  37.69911184,  43.98229715,  50.26548246,
        56.54866776,  62.83185307,  69.11503838,  75.39822369,
        81.68140899,  87.9645943 ,  94.24777961, 100.53096491,
       106.81415022, 113.09733553, 119.38052084, 125.66370614,
       131.94689145, 138.23007676, 144.51326207, 150.79644737,
       157.07963268, 163.36281799, 169.64600329, 175.9291886 ,
       182.21237391, 188.49555922, 194.77874452, 201.06192983,
       207.34511514, 213.62830044, 219.91148575, 226.19467106,
       232.47785637, 238.76104167, 245.04422698, 251.32741229,
       257.61059759, 263.8937829 , 270.17696821, 276.46015352,
       282.74333882, 289.02652413, 295.30970944, 301.59289474,
       307.87608005, 314.15926536, 320.44245067, 326.72563597,
       333.00882128, 339.29200659, 345.57519189, 351.8583772 ,
       358.14156251, 364.42474782, 370.70793312, 376.99111843,
       383.27430374, 389.55748905, 395.84067435, 402.12

In [24]:
Y = linearFunction(X, True)
Y

array([  6.57532996,  12.85851526,  19.14170057,  25.42488588,
        31.70807118,  37.99125649,  44.2744418 ,  50.55762711,
        56.84081241,  63.12399772,  69.40718303,  75.69036833,
        81.97355364,  88.25673895,  94.53992426, 100.82310956,
       107.10629487, 113.38948018, 119.67266548, 125.95585079,
       132.2390361 , 138.52222141, 144.80540671, 151.08859202,
       157.37177733, 163.65496264, 169.93814794, 176.22133325,
       182.50451856, 188.78770386, 195.07088917, 201.35407448,
       207.63725979, 213.92044509, 220.2036304 , 226.48681571,
       232.77000101, 239.05318632, 245.33637163, 251.61955694,
       257.90274224, 264.18592755, 270.46911286, 276.75229816,
       283.03548347, 289.31866878, 295.60185409, 301.88503939,
       308.1682247 , 314.45141001, 320.73459531, 327.01778062,
       333.30096593, 339.58415124, 345.86733654, 352.15052185,
       358.43370716, 364.71689246, 371.00007777, 377.28326308,
       383.56644839, 389.84963369, 396.132819  , 402.41